
services:
  postgres:
    image: postgres:15
    container_name: ia_trabalhista_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ia_trabalhista
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: